//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "users"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub username: Option<String>,
    pub language: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub subscription_tier: Option<String>,
    pub subscription_expires: Option<DateTimeUtc>,
    pub live_trading_enabled: Option<i8>,
    pub telegram_id: Option<String>,
    pub fullname: Option<String>,
    pub points: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Username,
    Language,
    CreatedAt,
    SubscriptionTier,
    SubscriptionExpires,
    LiveTradingEnabled,
    TelegramId,
    Fullname,
    Points,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ExchangeTokens,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::Username => ColumnType::Text.def().null(),
            Self::Language => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::Timestamp.def().null(),
            Self::SubscriptionTier => ColumnType::Text.def().null(),
            Self::SubscriptionExpires => ColumnType::Timestamp.def().null(),
            Self::LiveTradingEnabled => ColumnType::TinyInteger.def().null(),
            Self::TelegramId => ColumnType::Text.def().null(),
            Self::Fullname => ColumnType::Text.def().null(),
            Self::Points => ColumnType::BigUnsigned.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ExchangeTokens => Entity::has_many(super::exchange_tokens::Entity).into(),
        }
    }
}

impl Related<super::exchange_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExchangeTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
