//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub language: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    #[sea_orm(column_type = "Text", nullable)]
    pub subscription_tier: Option<String>,
    pub subscription_expires: Option<DateTimeUtc>,
    pub live_trading_enabled: Option<i8>,
    #[sea_orm(column_type = "Text", nullable)]
    pub telegram_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub fullname: Option<String>,
    pub points: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::exchange_tokens::Entity")]
    ExchangeTokens,
}

impl Related<super::exchange_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExchangeTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
